### ISSUE TITLE
Zombie Villagers with these new jobs show up as Black and Pink no texture found

### ISSUE THREAD

**Issue by campbebj** [samedifferent/morevillagers#1]
Zombie Villagers with these new jobs show up as Black and Pink no texture found

**Comment by samedifferent** [comment]
Thanks for letting me know, I just fixed it and the new update is live on Curseforge right now :)

**Comment by campbebj** [comment]
Sorry im waiting on the fabric one that i pulled down earlier today. you uploaded the forge one and the fabric download dissapeared....

**Comment by samedifferent** [comment]
Don't worry, the fabric version will be up by tomorrow on a new project page on curseforge. I wanted to have the forge and fabric versions on different curseforge project pages so modpack makers don't get confused and it makes it easier to update. I'll add a link to the fabric version as soon as it gets approved by curseforge :)
