### ISSUE TITLE
Crafting recipes do not work

### ISSUE THREAD

**Issue by FunkyPoseidon** [samedifferent/morevillagers#11]
## Bug Report

[ All of the lines between [ ] (square brackets) should be deleted before posting. ]

### What's the issue you encountered?
When I tried to craft the workstations using the crafting recipes listed on the wiki, they don't work. I also can't /give them to myself.
[ Describe the issue in detail and what you were doing beforehand. ]
I was trying to craft the workstations for my villager trading hall.
### How can the issue be reproduced?
Try to craft the workstations.
[ Include a detailed step-by-step process for recreating your issue with only More Villagers installed. ]
1. Try to use the crafting recipes.
### Mod Version
1.17-2.0.1
[ Please put the version of More Villagers that you were using here. ]

### Images, Videos, or Logs
![2021-06-26_14 08 11](https://user-images.githubusercontent.com/86534992/123524519-233c9000-d688-11eb-8df0-bfd9c3d206db.png)

[ Please include any relevant images, videos, or logs here. This can be done by dragging and dropping your files into the issue. ]

**Comment by PheonixVX** [comment]
Can you provide a full game log (E.g. Open MC, load a world, and open a crafting table)? The fact that you cannot /give yourself the blocks is extremely concerning.

**Comment by samedifferent** [comment]
Also, are you using any other mods besides More Villagers? To prove the issue is with More Villagers and not another mod, you will need to remove all other mods (including optifine/sodium) to see if the issue still occurs.
