### ISSUE TITLE
Cannot Download the Newest Version of the Mod

### ISSUE THREAD

**Issue by BobbyLinMC** [samedifferent/morevillagers#12]
## Bug Report

[ It seems that I cannot get the newest version of the the Minecraft More Villagers Mod. ]

### What's the issue you encountered?

[ I found this fantastic mod recently and downloaded a few days ago (before the newest version of the mod was released). Just yesterday, I found out that there was a new update, which is the Mod Version 1.5.2. The version I downloaded was 1.5.1. So when I saw the 1.5.2 update, I deleted the 1.5.1 and downloaded the 1.5.2. The downloading process was successful, but when I went to check the mod in the mods list in Minecraft, it said that the Mod Version I had was 1.5.1, instead of 1.5.2. I do not know what I did wrong. Please help!!!]

### How can the issue be reproduced?

[ Maybe I do not have the correct version of Forge? I have the Forge Version 36.1.31. ]

### Mod Version

[ I was using the Mod Version 1.5.1. The version I want is 1.5.2. ]

### Images, Videos, or Logs

[ Please include any relevant images, videos, or logs here. This can be done by dragging and dropping your files into the issue. ]

**Comment by samedifferent** [comment]
So I see that I forgot to change the version number in the mod's info file :P So you are using the 1.5.2 version, it just says 1.5.1 inside the mod list because I forgot to change that. I think I might change that in a 1.5.3 release, which will also add to the language files. But don't worry, you are using the latest version, 1.5.2, it just has the wrong number.

**Comment by BobbyLinMC** [comment]
Ohhh, I see. Do there aren't any major updates, I'm guessing? Like did you add any new villager professions? Also, thanks for commenting quick, I appreciate it. :)

**Comment by samedifferent** [comment]
There are no new features, but the update was very important because it fixed a critical bug regarding one of the villager houses. I got the update out as soon as possible to make sure nobody else experienced the bug, but I forgot to change the mod version before compiling.

**Comment by BobbyLinMC** [comment]
Oh okay. I see. I know I already asked this but when is 1.5.3 coming out? I'm just really excited.

**Comment by samedifferent** [comment]
It will come out when it's done. If you would like to keep up with the mod's development, I would suggest joining my discord server (https://discord.gg/87tmYg2VSj), where I post announcements about the mod and even allow people to download the updates early and test them out :)

**Comment by BobbyLinMC** [comment]
Oh ok. Thanks for replying. I will be keeping up with the mod's update. 👍
