### ISSUE TITLE
More Villager Professions Suggestion

### ISSUE THREAD

**Issue by BobbyLinMC** [samedifferent/morevillagers#14]
## Feature Request

[ My feature suggestions for more villagers update in the future are: Miner Villager (with a backpack), Doctor Villager, Zoologist Villager, Explorer Villager, Monk Villager, Rancher Villager, Astronomer Villager, Scientist Villager, and Necromancer Villager.  ]

### What feature are you suggesting?

[ The features I want to suggest are the villagers listed above. ]

### Why should it be added?

[ These features can be added so that it spices the mod up with more varieties of profession. For the trades that do not exist in the game you can add them to the mod. I understand that you might not be able to add all the villagers to the mod in the future update, because adding new trades and items might be a lot of work. :) ]
![download](https://user-images.githubusercontent.com/86644171/124150086-3cde3d00-dab7-11eb-83a3-efddfca8c4ed.jpg)

**Comment by samedifferent** [comment]
These sound like some interesting ideas, but are you able to come up with 10 items that they'd buy and sell? Vanilla Minecraft only has a limited number of items, and most of them are being sold by villagers already. Soon we will add villagers that sell items from some other popular mods like Farmer's Delight, Twilight Forest, and a few others. Thank you for your suggestion!
