### ISSUE TITLE
Issue with optifine, and villager textures

### ISSUE THREAD

**Issue by JoeA42** [samedifferent/morevillagers#15]
## Bug Report

[ All of the lines between [ ] (square brackets) should be deleted before posting. ]

### What's the issue you encountered?

When playing with optifine and this [texture pack ](https://resourcepack.net/default-plus-resource-pack/) the new villagers textures are warped and deformed around the villager face

### How can the issue be reproduced?

download the resourcepack and summon one of the new villagers

### Mod Version

morevillagers-FORGE-1.16.5-1.5.2.jar

### Images, Videos, or Logs

![image](https://user-images.githubusercontent.com/36778393/124369645-193c0380-dc2b-11eb-89d7-6b84d8e40f88.png)

**Comment by samedifferent** [comment]
Don't use Optifine, it's an issue on their side. They are closed source and therefore I can not fix it.

**Comment by JoeA42** [comment]
I understand, however I had an idea for an alternative  solution, if I make a resource pack for the skins of the new villagers it could override the original skin, that is warping around the villager, if you could, would you mind sharing the villager clothing, so I can create a resource pack?

**Comment by PheonixVX** [comment]
@JoeA42 Mods have internal resource packs. Here's the resource pack location: https://github.com/samedifferent/morevillagers/tree/main/src/main/resources/assets/morevillagers
