### ISSUE TITLE
hello, i have the more villagers mod (version 1.17-2.0.1) on my fabric server (fabric 0.7.4 and API version 0.36.0). When I place down the work stations none of the villagers take the jobs. I DO NOT have Sodium Reforged installed anywhere. How can I fix this?

### ISSUE THREAD

**Issue by notabbylol** [samedifferent/morevillagers#16]
### What's the issue you encountered?

When I place down the villager workstations none of them take the job. I do NOT have sodium reforged installed so that cannot be the issue.

### How can the issue be reproduced?

Using a fabric server with more villagers installed.

### Mod Version

Version 2.0.1

### Images, Videos, or Logs

[ Please include any relevant images, videos, or logs here. This can be done by dragging and dropping your files into the issue. ]

**Comment by samedifferent** [comment]
Were you able to recreate the issue with no other mods installed? (Also, in bug reports, please actually fill out the template that we provided.)

**Comment by notabbylol** [comment]
I will try it out with no other mods.

**Comment by notabbylol** [comment]
okay it worked with no other mods. I will try to test which mod is incompatible. Thank You!

**Comment by samedifferent** [comment]
Please let me know which mod it is
