### ISSUE TITLE
BetterNether/BetterEnd integration.

### ISSUE THREAD

**Issue by SoldierKucha** [samedifferent/morevillagers#17]
## Feature Request
I request an integration with BetterNether and BetterEnd, since More Villagers adds vendors, dependent on said dimensions. Thus, adding extra trade variants with items from listed mods or even extra villager jobs: BetterNether adds nether counterparts to certain overworld crafting stations, such as Furnaces for different nether rocks (Basalt, Blackstone, Netherrack), nether brewing stand and Cincinnasite forge (Cincinnasite being new metal added by BetterNether). BetterEnd adds End counterparts too, as well as new metals and a BetterEnd specific crafting station - Infusion Altar. 

### What feature are you suggesting?

Here i will list jobs, some of which are just more specific variants of Netherologist and Enderologist. By "/" i will define a variant of a trade, meaning one of the listed will be in the spot.

N͟E͟T͟H͟E͟R͟ S͟M͟I͟T͟H͟
Workstation: Cincinnasite Forge
**Level 1 Trades:**
4 Cincinnasite -> 1 Emerald
1 Emerald -> 1 Blue Obsidian
**Level 2 Trades:**
1 Nether Ruby -> 1 Emerald
4 Obsidian + 1 Emerald -> 4 Obsidian Glass/4 Blue Obsidian + 1 Emerald -> 4 Blue Obsidian Glass
**Level 3 Trades:**
4-7-5-9 Emeralds -> Cincinnasite armor piece (boots, leggings, helmet and chestplate respectively)
Cincinnasite tool, unenchanted + 4 Emeralds -> Cincinnasite-diamond tool
**Level 4 Trades:**
36 Emeralds -> Cincinnasite Anvil
8 Emeralds -> Cincinnasite fire bowl/Cincinnasite soul fire bowl (if villager is in the nether)
**Level 5 Trades:**
36 Emeralds -> Respawner Statue

N͟E͟T͟H͟E͟R͟ H͟E͟R͟B͟A͟L͟I͟S͟T͟
Workstation: Nether Brewing Stand
**Level 1 Trades:**
6 Stalagnate Seed -> 1 Emerald/20 Nether Reed -> 1 Emerald
1 Emerald -> 1 Crimson Nylium/1 Warped Nylium
**Level 2 Trades:**
6 Eye Seed -> 1 Emerald/6 Lumabus -> 1 Emerald/6 Golden Lumabus -> 1 Emerald
1 Emerald -> 2 Agave Medicine
**Level 3 Trades:**
6 Wart Seed -> 1 Emerald/6 Willow Sapling -> 1 Emerald/6 Rubeus Sapling -> 1 Emerald
1 Emerald -> 3 Ink Bush Seed/3 Blooming Vine
**Level 4 Trades:**
6 Nether Sakura Sapling -> 1 Emerald/6 Anchor Tree Sapling -> 1 Emerald
3 Emerald -> Feather Fern/3 Emerald -> Magma Flower Seed
**Level 5 Trades:**
4 Emerald -> 1 Herbal Medicine

That would be it for BetterNether. I would also planned a list of trades specifically for mushrooms (honestly, there is tons of them in that mod) but there is no crafting station that at least hints on being connected to mushrooms and Nether Herbalist trades are already feel bloated, had to think of cutting some of them. As for BetterEnd i would add Ender Shards as a possible variant of an Enderologist's 3rd Level trade - 14 Ender Shards instead of 14 Ender Pearls and add BetterEnd's wood variants of composters to the Farmer workstations.
 
E͟N͟D͟E͟R͟ S͟M͟I͟T͟H͟
Workstation: End Stone Smelter
**Level 1 Trades:**
8 Leather Wrapped Stick -> 1 Emerald
3 Ender Pearls + 1 Emerald -> 3 Ender Dust
**Level 2 Trades:**
6 Sulfur -> 1 Emerald
1 Iron Ingot + 2 Emerald -> Iron Bulb Lantern (only if villager is in the end)
**Level 3 Trades:**
3 Raw Amber -> 1 Emerald
5 Emerald -> Thalassium Hammer
**Level 4 Trades:**
Thalassium Hammer + 6 Emerald -> Terminite Hammer
4 Iron Ingot + 4 Emerald -> 2 Terminite
**Level 5 Trades:**
16 Emerald - Infusion Pedestal

Leather wrapped sticks, raw amber, thalassium, terminite, ender dust - are all added by BetterEnd, as well as Iron Bulb Lantern. There is currently no workstation that could be associated with herbalist or mycologist (BetterEnd's End also has tons of mushrooms).

### Why should it be added?

Firstly - your mod is really great and heavily impacts village based playthroughs, such as one i am committing right now, and thus the more it grows - the better experience in such playthrough would be. Secondly - the more cross-mod interaction there is - the more game feels whole, when all content is in-line with each other, increasing the immersion.

**Comment by Toma400** [comment]
Strongly agree, though - the same as with core mod - I'd love to see trades being a bit more balanced. Vanilla trades are already OP when you "zombie-doctorify" the villager, but More Villagers trades are OP even without it. Would be cool to consider balance also in this feature (for example 3 ender pearls + 1 emerald is really cheap for something which by anvil is really tough to get, I'd require much more emeralds for that pricy item)
