### ISSUE TITLE
Multiplayer server crash. Leveling up Netherologist from journeyman

### ISSUE THREAD

**Issue by 96curt** [samedifferent/morevillagers#18]
### What's the issue you encountered?

[ The multiplayer server crashes. ]

### How can the issue be reproduced?

[ By leveling up Netherologist from Journeyman. ]

### Mod Version

[ 2.0.4 ]

### Images, Videos, or Logs
[
     [17:38:24] [Worker-Main-10/WARN]: Empty or non-existent pool: minecraft:village/                        common/villagers
]

### Notes 
 After resetting server villager is back to journey man level.

**Comment by samedifferent** [comment]
Are you able to replicate the issue with only More Villagers and no other mods installed?

**Comment by PhoenixVX** [comment]
Without any logs, it is impossible to tell what is wrong. And the log you posted has absolutely nothing to do with the issue. We register our villagers the same way as vanilla, so unless this is a vanilla issue, I don't see why it would crash. 

Please respond with adequate logs if you wish to get help.
