### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by BobbyLinMC** [samedifferent/morevillagers#23]
## Bug Report

[ Currently I'm playing on Minecraft 1.16.5. Since the new update vers. 1.17.1 came out along with the miner villager, I really want  the miner villager. ]

### What's the issue you encountered?

[ I did not encounter any issue, but I have a question. Can I use the 1.17.1 mods vers. for my 1.16.5? ]

### How can the issue be reproduced?

[ - ]

### Mod Version

[ Currently playing on 1.16.5. ]

### Images, Videos, or Logs

[ Please include any relevant images, videos, or logs here. This can be done by dragging and dropping your files into the issue. ]

**Comment by samedifferent** [comment]
All of the trades that the miner has are items that were released in Minecraft 1.17. 1.16.5 does not have amethyst, raw ores, calcite, deepslate, and the other items that the miner sells. So therefore I cannot backport the Miner to 1.16.5 because it does not have those items.

**Comment by samedifferent** [comment]
However, if you are able to find a mod that adds all of the 1.17 blocks and items to 1.16.5, then I might add compatibility with that mod.

**Comment by BobbyLinMC** [comment]
So I found this mod that backports most 1.17 blocks to older game vers.
Here's the link to the mod:)
https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs/files

**Comment by samedifferent** [comment]
I will consider it. Please join my discord server if you would like to discuss the mod further.
