### ISSUE TITLE
Villager not being able to locate their work stations

### ISSUE THREAD

**Issue by SpinoFTW** [samedifferent/morevillagers#25]
I was playing with the More Villagers mod and noticed that some of the villagers weren't getting those professions from their workstations. I tried looking into the logs but couldn't find anything,
![2021-08-16_12 17 19](https://user-images.githubusercontent.com/72393243/129603800-101e1a6c-e35c-41ce-a616-1bc77fd88e0d.png) Here is picture showing that villagers aren't going to their workstations
[Spino TestPack 1.16-test.zip](https://github.com/samedifferent/morevillagers/files/6994215/Spino.TestPack.1.16-test.zip)
Here is the modpack I was using
[latest.log](https://github.com/samedifferent/morevillagers/files/6994223/latest.log)
and here is the lastest log from the modpack
hope you have a great day!

**Comment by samedifferent** [comment]
Are you using Sodium Reforged? If so, go into the config file called `sodium-mixins.properties`, and just type `mixin.ai=false`

**Comment by SpinoFTW** [comment]
thank you so much

**Comment by SpinoFTW** [comment]
actually it doesn't work

**Comment by PhoenixVX** [comment]
Closing issue as seems resolved.
