### ISSUE TITLE
Getting a Netherologist to Level 4 in the Overworld will cause a crash

### ISSUE THREAD

**Issue by tioalexis** [samedifferent/morevillagers#29]
### What's the issue you encountered?

This happens in the Better Minecraft (Fabric) 1.17.1 modpack. This does not happen in a Vanilla world.

The game crashes when you level up a Netherologist in the overworld. The crash does not happen when you level up the Netherologist from within the Nether dimension.
- In single player (tested in creative mode), the villager will be uninteractable.
- In multiplayer, the server will freeze and eventually crash.

### How can the issue be reproduced?

1. Install the Better Minecraft (Fabric) 1.17.1 modpack.
2. Start a Creative World.
3. Spawn a Villager and a Decayed Workbench in the overworld.
4. Level up the Netherologist three times (Level 4).
5. Attempt to interact with the villager. The villager will be uninteractable.
6. If you wait enough time (around 5 minutes in my PC), the game will continue to run again and the villager will level up as normal.

You can also try this in multiplayer. Just get a Netherologist to Level 4 in the overworld.

### Mod Version

MultiMC reports the mod version to be `2.0.4-SNAPSHOT` but the actual mod file name is `morevillagers-FABRIC-1.17-2.0.4.jar`

### Images, Videos, or Logs

https://user-images.githubusercontent.com/83507082/131249231-7525965a-05a7-4b49-8635-0afc6cca9079.mp4

This is the crash log I got from the server but it doesn't seem relevant.
[crash-log.txt](https://github.com/samedifferent/morevillagers/files/7072400/crash-log.txt)

**Comment by tioalexis** [comment]
Tested it on a vanilla world (only this mod installed). It did not crash.

**Comment by tioalexis** [comment]
Also attached the crash logs but I don't think it's relevant.

**Comment by tioalexis** [comment]
Upon further testing, if you wait for the game (around 5 minutes on my PC), it will eventually run again and the Netherologist will level up as intended.

**Comment by samedifferent** [comment]
Since the issue does not occur when playing with only More Villagers, this issue is not with our mod. d
