### ISSUE TITLE
Error when trying to grab an achievement 

### ISSUE THREAD

**Issue by nsherbina1999** [samedifferent/morevillagers#34]
Hello. When I'm trying to start my server, there is an error (not fatal), which tells:

> [13:55:44] [Worker-Main-3/ERROR]: Parsing error loading custom advancement morevillagers:all_workstations_get: Unknown required criterion 'miningbench'

It's not too critical, but I think it needs to be fixed.

**Comment by samedifferent** [comment]
This has been fixed in the latest version

**Comment by nsherbina1999** [comment]
Thanks!
