### ISSUE TITLE
[Bug]: Netherian Crash

### ISSUE THREAD

**Issue by AppDevMichael** [samedifferent/morevillagers#37]
### Mod Version

2.1.1

### Mod Loader

Fabric

### Mod Loader Version

11.3

### What happened?

When using this mod with WilliamWythersOverhauledOverworld-1.7(1.17.x) the server can hang and crash.

To reproduce, promote a Netherian past tier 3.

### latest.log

[latest.log](https://github.com/samedifferent/morevillagers/files/7619863/latest.log
[crash-2021-11-29_15.09.28-server.txt](https://github.com/samedifferent/morevillagers/files/7619868/crash-2021-11-29_15.09.28-server.txt)
)

**Comment by SharkieTV** [comment]
all more vilalger crash im pretty ssure

**Comment by PhoenixVX** [comment]
Interesting issue, William's mods appear to have an open source license, but no open source available? If I can find the source code (I don't like infringing on people's rights by decompiling their mod unless absolutely need to), it should be easy to fix.
