### ISSUE TITLE
Can't use workstations

### ISSUE THREAD

**Issue by NatersColl** [samedifferent/morevillagers#4]
My 2 friends and I started to build a trading hall filled with engineers (using Iron, pistons and lamps as decoration) when the villagers stopped sinking with workstations. Last night it was working fine, but today none of them would get a profession. Overnight we had our villager breeders working, leaving us with around 150 villagers nearby. None of the ones in the area were linked up to the workstations, so we don't know what happened. I will attach a picture of the hall we were storing them in.
![2021-06-03_18 11 15](https://user-images.githubusercontent.com/73314375/120719283-01d8f180-c498-11eb-8351-9bde8f5315e4.png)

**Comment by samedifferent** [comment]
I'm sorry you're having this issue, but you did not follow all the directions that I wrote In the "Issues" section of the mod description. There are some more things I need you to include in your issue report before we can figure out how to solve the problem. Thank you :)

**Comment by NatersColl** [comment]
Sorry about that.

Fabric: 0.7.3
Fabric API: 0.30.0
Version: The newest version of the mod
Other villager mods: no this is the only villager mod we are using, though we have one that gives wandering traders better trades

**Comment by samedifferent** [comment]
I spoke to the fabric developer and he might need some more information before being able to help you. Are you able to join our discord server where we can do some more detailed troubleshooting? Here's the invite link: [https://discord.gg/87tmYg2VSj](https://discord.gg/87tmYg2VSj)

**Comment by PheonixVX** [comment]
Try the latest 1.4.0 Fabric version that should be up in some time. Also, your Fabric API version is outdated by at least 2-3 major versions. Also, you listed your "Fabric" version as 0.7.3 which if I am assuming is correct, would be the installer version, not the loader version. You can check at the top of your server logs as for the fabric loader version. As said before, further assistance can be provided on our discord server.

**Comment by NatersColl** [comment]
I joined the discord server as Builder_master

**Comment by LucasJoel1** [comment]
Fabric version is 0.11.3
