### ISSUE TITLE
Mobs aren't rendering

### ISSUE THREAD

**Issue by toffi3** [samedifferent/morevillagers#5]
Unluckly, the issue is still there, it started when i added your mod, when i deleted it, everything worked as it should so please check it out. Here's the quick footage of the issue https://www.youtube.com/watch?v=j-CW3e7PrZ4

**Comment by PheonixVX** [comment]
Can you provide additional information such as modloader, mod list, mod version, etc. following the issue template?

**Comment by toffi3** [comment]
I've done it in pastbin since i had to crash minecraft to copy my mods, here is i think everything you need: https://pastebin.com/3h2LFQcd

**Comment by samedifferent** [comment]
To prove this is an issue with our mod, you need to be able to give us the steps to recreate the issue **in a new world** with **only More Villagers installed** -- **no other mods** and **no Optifine**. If the issue still occurs in a new world even after uninstalling every other mod except for More Villagers, then we can look into it. But as of what you have provided now, there is no evidence to suggest that our mod is the cause for this.
