### ISSUE TITLE
[Bug]: Villagers won't take jobs

### ISSUE THREAD

**Issue by Th3DJLucipurr** [samedifferent/morevillagers#50]
### Mod Version

3.2.0

### Mod Loader

Forge

### Mod Loader Version

40.1.0

### What happened?

I am currently playing on a modpack called "Better Minecraft" for 1.18.2 and the the villagers won't take their jobs. It seems to be an incompatibility issue since the mod works fine when I remove all the other mods. The modpack does have sodium-reforged and I did test adding that line of code from a previous issue submission, but it didn't fix it.
![Screenshot (37)](https://user-images.githubusercontent.com/61002948/167217709-937769a3-c477-4812-947f-cfcc83f4b27b.png)

### latest.log

[latest.log](https://github.com/samedifferent/morevillagers/files/8643672/latest.log)

**Comment by SirUmnei** [comment]
Can confirm, having the same issue, although my modpack is a custom one.

**Comment by ghost** [comment]
Same As The Abouve Guy

**Comment by samedifferent** [comment]
Try removing sodium reforged

**Comment by oOCredo** [comment]
Same issue here. No Sodium Reforged installed. Crafting Recipes are working, Villager just dont take the Jobs. 
Minecraft 1.18.2 and Forge 40.1

**Comment by samedifferent** [comment]
Are you using a different performance mod? Performance mods tend to interfere with villager AI.

**Comment by oOCredo** [comment]
You were right. It was another Performance Mod : Radium. Removing it fixed it.
Thanks you!! and also thanks for the fast reply :)

**Comment by samedifferent** [comment]
To fix it, you can add `mixin.ai.poi=false` in the radium config file

**Comment by Th3DJLucipurr** [comment]
Removing mods would be less than ideal from a modpack. The point of a performance enhancing mod in a modpack is that you are able to run many mods. So are you not even gonna attempt to fix it? Cause then I should just let the modpack creator for Better Minecraft know that your mod doesn't work and the creator has no intention of getting it to work.

**Comment by Th3DJLucipurr** [comment]
For anyone else who gets stuck, I put `mixin.ai.poi=false` to the Soidum, Radium and Rubidium config files. This should get it to work.
