### ISSUE TITLE
profession's own modid

### ISSUE THREAD

**Issue by Laifsyn** [samedifferent/morevillagers#52]
### Mod Version

1.18.2-3.2.0

### Mod Loader

Fabric

### Mod Loader Version

0.14.6

### What happened?

I was checking my CraftTweaker's dumps, and I noticed that your profession shares the same namespace as vanilla Minecraft(aka. minecraft:engineer ). I would suggest to change the namespace to the mod's name for generalization sakes 

### latest.log

nan

**Comment by samedifferent** [comment]
This only occurs on fabric, and vanilla just decides to use the Minecraft namespace for them. I noticed this with other mods that add new villagers, so I don't think it's something I can change, and it doesn't affect anything.
