### ISSUE TITLE
Achievement not unlockable glitch

### ISSUE THREAD

**Issue by emanuele246gi** [samedifferent/morevillagers#53]
I'm playing More Villagers 3.2.0 in 1.18.2 with Forge 40.1.48: when I go in a village, it doesn't unlock the "first village" achievement, I ran into this problem a long ago but, for some reason, I was sure it was fixed.

**Comment by samedifferent** [comment]
Fixed in latest 1.18.2 and 1.19 versions

**Comment by emanuele246gi** [comment]
Thank you
