### ISSUE TITLE
Crash Log after update

### ISSUE THREAD

**Issue by ardissaps** [samedifferent/morevillagers#54]
https://paste.atlauncher.com/view/6458274e-2523-4cfe-bcba-b7952597c216

**Comment by samedifferent** [comment]
Are you able to reproduce the issue with only More Villagers and no other mods installed?

**Comment by ardissaps** [comment]
> Are you able to reproduce the issue with only More Villagers and no other mods installed?

Previous version works fine with all installed mods, is there significant change? Does the log does not give clue?   Now I am downgrade the version as it is impossible for me as regular player to check one by one compatibility.

**Comment by samedifferent** [comment]
Try updating to the latest version of Oh The Biomes You'll Go. The error seems to be coming from that mod, which you are using an older version of.

**Comment by CorgiTaco** [comment]
if that doesnt work reset trades config

**Comment by ardissaps** [comment]
> if that doesnt work reset trades config

this one surprisingly fixed the problem, now I can update MoreVillager with peace! Thanks! :)

> Try updating to the latest version of Oh The Biomes You'll Go. The error seems to be coming from that mod, which you are using an older version of.

that was OBYG latest version for 1.18.2, they move further update to 1.19, thank you for the mods sir! :)
