### ISSUE TITLE
[Bug]: Cant properlly uninstal...

### ISSUE THREAD

**Issue by JKaiya** [samedifferent/morevillagers#55]
### Mod Version

Newest

### Mod Loader

Forge

### Mod Loader Version

Newest

### What happened?

I uninstalled the mod as I needed to lessen the amount of mods I have to run the game properly... but this mod seems to possibly break the game once deleted. At the very least, Oh the biomes you'll go is broken and needs to be deleted once you delete this mod. Even if I redownload that it is still broken due to whatever code this mode made when it ran

### latest.log

[crash-2022-06-17_02.48.16-fml.txt](https://github.com/samedifferent/morevillagers/files/8926535/crash-2022-06-17_02.48.16-fml.txt)

**Comment by JKaiya** [comment]
[lasdgatest.log](https://github.com/samedifferent/morevillagers/files/8926552/lasdgatest.log)

**Comment by JKaiya** [comment]
I managed to fix it by deleting the byg config file from All the biomes you'll go that this mod changed

**Comment by samedifferent** [comment]
This was fixed in the latest version of BYG. Please use the latest version of BYG.
