### ISSUE TITLE
[Bug]: Villagers won't take jobs

### ISSUE THREAD

**Issue by Ekqo3** [samedifferent/morevillagers#63]
### Mod Version

3.3.2

### Mod Loader

Forge

### Mod Loader Version

40.1.60

### What happened?

Same issue as #50, modpack is [Triforge](https://www.curseforge.com/minecraft/modpacks/triforge). Adding `mixin.ai.poi=false` to the Rubidium and Radium config files causes client to crash on loading world.

### latest.log

[latest.log](https://gist.github.com/Ekqo3/1d9121609a152b85e0e1367614f2fc15)

**Comment by samedifferent** [comment]
Please report this issue to Rubidium/Radium. The issue is completely on their end and I have no control over it. More Villagers works properly on its own.
