### ISSUE TITLE
wrong datapcack (outdated)

### ISSUE THREAD

**Issue by gamingoninsulin** [samedifferent/morevillagers#7]
its a kinda bug-ish 

i wat entering a other datapack trough the ingame menu an discoverd that nmorevillagers datapack is for an older veresion probably 1.16 (6) and not 1.17 (7)

**Comment by samedifferent** [comment]
You did not follow the issue template. When you created an issue, there were specific questions you had to answer. We cannot resolve the issue unless we have all of that information. Please click the new issue button, select bug report, copy all the information there, and then reply to this issue with all of the necessary information. Thank you.

**Comment by PheonixVX** [comment]
I think they are referring to this:
https://github.com/samedifferent/morevillagers/blob/fabric-1.17/src/main/resources/pack.mcmeta

Specifically, the 6 in there should be a 7.

**Comment by gamingoninsulin** [comment]
yes i reffering to the datapack form ithe mod like @PheonixVX  said

**Comment by PheonixVX** [comment]
Is it of such importance that we need to push a hotfix out? Or is it fine if we push this next release?

**Comment by gamingoninsulin** [comment]
sure its fine w anted only to let you know ;)

**Comment by PheonixVX** [comment]
Alright thank you, closing until further notice.
