### ISSUE TITLE
[Bug]: Incompatible with Radium Reforged

### ISSUE THREAD

**Issue by Ceimnithe** [samedifferent/morevillagers#73]
### Mod Version

3.3.2

### Mod Loader

Forge

### Mod Loader Version

40.1.86

### What happened?

Noticed that villagers weren't recognizing the More Villagers jobsite blocks in my setup. By process of elimination, found out Radium Reforged was the culprit, so I figured I should give a heads up. When that mod is removed, they become employed normally.

More Villagers 3.3.2
Radium Reforged 0.7.10
Forge 40.1.86

### latest.log

[latest.log](https://github.com/samedifferent/morevillagers/files/10243979/latest.log)

**Comment by samedifferent** [comment]
This is a "feature" of radium. They disable custom villager professions by default to apparently improve performance. This has been reported to them many times and they will not fix it. To enable them, go into the radium properties config and add `mixin.ai.poi = false`
