### ISSUE TITLE
[Bug]: Villagers not detecting workstations from More Villagers and workstations can't be put into Traders from Easy Villagers

### ISSUE THREAD

**Issue by SirWishbone** [samedifferent/morevillagers#74]
### Mod Version

1.18.2-3.3.2

### Mod Loader

Forge

### Mod Loader Version

40.1.69

### What happened?

I have the More Villagers mod loaded and it works to an extent. I can see the workstations and craft them and mods like Just Enough Items shows that trades can be made with the villagers added by the More Villagers Mod. But unemployed villagers will not take to the workstations and change their employment. I also can't put these workstations in the Traders added by Easy Villagers. I know that Easy Villagers and More Villagers are compatible and I've played with them together without issue. 

### latest.log

[latest.log](https://github.com/samedifferent/morevillagers/files/10252461/latest.log)

**Comment by samedifferent** [comment]
The issue is with the mod Radium Reforged. See my response on this issue report for the solution: https://github.com/samedifferent/morevillagers/issues/73

**Comment by SirWishbone** [comment]
Thanks, that solved the issue!!!
