### ISSUE TITLE
Some broken advancements

### ISSUE THREAD

**Issue by Fourmisain** [samedifferent/morevillagers#9]
![anywood](https://user-images.githubusercontent.com/8464472/122630907-901fbb00-d0c7-11eb-8382-050061e574ca.png)
Creating a new world, picking up a log (or probably any item) will trigger these two advancements:
[first_workstation_get.json](https://github.com/samedifferent/morevillagers/blob/main/src/main/resources/data/morevillagers/advancements/first_workstation_get.json)
[all_workstations_get.json](https://github.com/samedifferent/morevillagers/blob/main/src/main/resources/data/morevillagers/advancements/all_workstations_get.json)

From my (poor) understanding, the JSON format very slightly changed in 1.17.
Item conditions need to e.g. use `"items": ["minecraft:blast_furnace"]` instead of `"item": "minecraft:blast_furnace"`.

**Comment by PheonixVX** [comment]
Commit hash 2b2c60a fixes most of the advancements save for 2.
